version: '3.8'
services:
    web:
      tty: true
      build: .
      volumes:
        - .:/usr/src/app
      ports:
        - 8080:8080
      expose: 
        - '8080' 
      restart: always
      command: npm run dev