name: Run Tests in Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose with Tests Action
      # You may pin to the exact commit or the version.
      # uses: adambirds/docker-compose-action@cf2e51f76beacad15b1046de89ee2eb22ea70bac
      uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "docker-compose.yml"
        services: "web"
        up-flags: "--timeout 120"
        test-container: "web"
        test-command: "npm run test"
